### ISSUE TITLE
Add new file types to extensiondict.py

### ISSUE THREAD

**Issue by sreekaransrinath** [sreekaransrinath/file_organizer#11]
extensiondict.py contains a dictionary of file types, extensions and where they should be placed in the file organization system.

While it is fairly extensive at the moment, I'm sure I haven't covered every file type possible.

Your mission, should you choose to accept it, is to add new file types (and the directories they belong in) to the extensiondict.py file.

This message will self-destruct in 5 seconds :P

**Comment by soulspark666** [comment]
If someone like to pick this up, then I found some good sites for your help https://fileinfo.com/filetypes/text and https://en.wikipedia.org/wiki/List_of_file_formats.

**Comment by sreekaransrinath** [comment]
@soulspark666 Good stuff bruh :)

**Comment by 0sf** [comment]
I would love to work on the issue.

**Comment by sreekaransrinath** [comment]
@0sf Go for it!

**Comment by 0sf** [comment]
Thank you very much! :) is it possible to add new sections ( like # log )

**Comment by sreekaransrinath** [comment]
Yeah, sure :)

**Comment by sk044** [comment]
It can be something new ….such as something related to 3d

**Comment by sreekaransrinath** [comment]
@sk044 Yep, it sure can!

**Comment by nishu88** [comment]
#26 Hope this is what you had in mind. Still many file extensions to take a crack at ;)

**Comment by rodrigondec** [comment]
I think it would be better to accept the existing merges before creating new ones? 
To avoid duplicated file types

**Comment by sudonitin** [comment]
Is this assigned? @sreekaran16  @nishu88?

**Comment by nishu88** [comment]
> Is this assigned? @sreekaran16 @nishu88?

No, I believe it's open for all. Go take a crack at it. ;)

**Comment by sreekaransrinath** [comment]
Nope, it's meant to be open for all, since this is not something like a bug fix or feature request where only one person can work on it at a time. 

This should also help first-timers and beginners increase their PR count for Hacktoberfest while making some meaningful contributions :)

**Comment by anshuldutt21** [comment]
#50

**Comment by anshuldutt21** [comment]
I added some more file formats. Please review. 
 #50
